name: Docker Image CI

on:
  push:
    branches: [ "cmolloy36/tooling/add-docker-image-building-workflow" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE_NAME: arthive-app-backend

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10.12'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_PINKPROTOCOL }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image for backend
        run: docker build ./backend -t ${{ secrets.DOCKER_USERNAME_PINKPROTOCOL }}/${{ env.BACKEND_IMAGE_NAME }}
        
      - name: push backend image to Docker Hub
        run: docker image push arthive-app-backend:latest
